SRC += muse.c

AUDIO_ENABLE = yes
RGBLIGHT_ENABLE = yes
MOUSEKEY_ENABLE = yes
UNICODE_ENABLE = yes
#JOYSTICK_ENABLE = digital
#MIDI_ENABLE = yes
ENCODER_ENABLE = yes
TAP_DANCE_ENABLE = yes
STENO_ENABLE = no
MOUSEKEY_ENABLE = yes
VIA_ENABLE = no
#AUTO_SHIFT_ENABLE = yes
VELOCIKEY_ENABLE = yes
I2C_NABLE = yes
WPM_ENABLE = Yes
